{% set name = "kpackage" %}
{% set version = "5.69.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kpackage-{{ version }}.tar.xz
  sha256: d740c4e159617dcf969584b94bc3e6f2c1da45c3a5d366f2be18decda0466e1b

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kpackage', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    #- {{ cdt('mesa-libgl-devel') }}  # [linux]
    #- {{ cdt('mesa-dri-drivers') }}  # [linux]
    #- {{ cdt('libselinux') }}  # [linux]
    #- {{ cdt('libxdamage') }}  # [linux]
    #- {{ cdt('libxxf86vm') }}  # [linux]
  host:
    #- xorg-libxfixes  # [linux]
    - qt
    - ki18n
    - karchive
    - kcoreaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Package.so

about:
  home: https://api.kde.org/frameworks/kpackage/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: 'Installation and loading of additional content (ex: scripts, images...) as packages'
  description: |
    The KPackage framework lets the user install and load packages of
    non binary content such as scripted extensions or graphic assets,
    as if they were traditional plugins.
  dev_url: https://cgit.kde.org/kpackage.git/tree

extra:
  recipe-maintainers:
    - scopatz
