{% set name = "kpackage" %}
{% set version = "5.76.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kpackage-{{ version }}.tar.xz
  sha256: 97791ef08ca18892d6aa6a50fa0a87ae72cad10de9f17e3fb503a370de829772

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kpackage', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
  host:
    - qt
    - ki18n >={{ major_minor }}
    - karchive >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Package.so

about:
  home: https://api.kde.org/frameworks/kpackage/html/index.html
  license: GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later
  license_file:
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
  summary: 'Installation and loading of additional content (ex: scripts, images...) as packages'
  description: |
    The KPackage framework lets the user install and load packages of
    non binary content such as scripted extensions or graphic assets,
    as if they were traditional plugins.
  dev_url: https://cgit.kde.org/kpackage.git/tree

extra:
  recipe-maintainers:
    - scopatz
