{% set name = "kpackage" %}
{% set version = "5.71.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kpackage-{{ version }}.tar.xz
  sha256: c4b924e7c506cb75bdaaf68bd881e79a73999bd6436f29157f56c76f32b48cba

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kpackage', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
  host:
    - qt
    - ki18n >={{ major_minor }}
    - karchive >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Package.so

about:
  home: https://api.kde.org/frameworks/kpackage/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: 'Installation and loading of additional content (ex: scripts, images...) as packages'
  description: |
    The KPackage framework lets the user install and load packages of
    non binary content such as scripted extensions or graphic assets,
    as if they were traditional plugins.
  dev_url: https://cgit.kde.org/kpackage.git/tree

extra:
  recipe-maintainers:
    - scopatz
